runtime: nodejs20

env: standard

service: default

instance_class: B1

vpc_access_connector:
    name: projects/granfondophotosearch/locations/asia-northeast3/connectors/gfps-connector
    egress_setting: all-traffic

handlers:
- url: /.*
  script: auto

manual_scaling:
  instances: 1
