import * as oMongoose from 'mongoose';
import reservedKeywords from '../utils/reservedKeywords';
// const reservedKeywords = require('../utils/reservedKeywords');
const Schema = oMongoose.Schema;


const UserSchema = new Schema({
    /**
     * id field automatically generated by mongoDB
     */
    username: {
        type: String,
        minlength: 4,
        maxlength: 64,
        required: true,
        unique: true,
    },
    pssword: {
        type: String,
        minlength: 4,
        maxlength: 128,
        required: true,
    },
    status: {
        type: String,
        enum: reservedKeywords.userStatusEnum,
        required: true,
    },
    email: {
        type: String,
        required: true,
        unique: true,
    },
    createdDate: {
        type: Date,
        default: Date.now,
        required: true
    },
    updatedDate: {
        type: Date,
        default: Date.now,
        required: true,
    },
    uploadedPhotos: [
        /**
         * Using ref field, we can reference to other model like photos in NoSQL database.
         */
        {   
            type: Schema.Types.ObjectId,
            ref: 'photos'
        }
    ]
});

/**
 * Modle Middle ware function setting
 */
UserSchema.pre('save', function (next) {
    const currentDate = new Date();
    this.updatedDate = currentDate;

    if (!this.createdDate) {
        this.createdDate = currentDate;
    }
    next();
})

export default oMongoose.model('users', UserSchema);