/**
 * @module User
 * 
 * @file User.ts is a model file which contains the interface of schema and model for user collection.
 * @description It is used to define the schema and model for user.
 * email field will be use for indetify the user.
 */

import * as oMongoose from 'mongoose';
import reservedKeywords from '../utils/reservedKeywords';
import config from '../config';
import { on } from 'events';

const oneDay = 60 * 60 * 24;

/**
 * Define interface for user model
 */
interface IUser extends oMongoose.Document {
    email: string;
    username: string;
    password: string;
    status: string;
    expireAt: Date;
    createdDate: Date;
    updatedDate: Date;
    uploadedPhotos: oMongoose.Schema.Types.ObjectId[];
}

/**
 * Define user schema and set middleware function.
 */
const Schema = oMongoose.Schema;
const UserSchema = new Schema({
    /**
     * id field automatically generated by mongoDB
     */

    // email use as id for user
    email: {
        type: String,
        required: true,
        unique: true,
    },
    name: {
        type: String,
        minlength: 4,
        maxlength: 64,
        required: true,
        unique: false,
    },
    // password field will be use to store the 'hashed' user password.
    pssword: {
        type: String,
        minlength: 4,
        maxlength: 128,
        required: true,
    },
    status: {
        type: String,
        enum: reservedKeywords.userStatusEnum,
        default: reservedKeywords.userStatusEnum[0],
        required: true,
    },
    /**
     * expireAt field will be use to store the expire date of email verification.
     * You can disable this feature by removing this field. or set the value to 9999-12-31.
     */
    expireAt: {
        type: Date,
        default: Date.now,
        expires: oneDay * config.emailVerificationExpiryDay,    // TTL setting for email verification.
    },
    createdDate: {
        type: Date,
        default: Date.now,
        required: true
    },
    updatedDate: {
        type: Date,
        default: Date.now,
        required: true,
    },
    uploadedPhotos: [
        /**
         * Using ref field, we can reference to other model like photos in NoSQL database.
         */
        {   
            type: Schema.Types.ObjectId,
            ref: 'photos'
        }
    ]
});

/**
 * Modle Middle ware function setting
 */
UserSchema.pre('save', function (next) {
    const currentDate = new Date();
    this.updatedDate = currentDate;

    if (!this.createdDate) {
        this.createdDate = currentDate;
    }
    next();
})

const User = oMongoose.model<IUser>('users', UserSchema);
export { User, IUser };